# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
path: datasets # dataset root dir
train: subset/images/train
  # - WIDER-FACE/WIDER_train/images
  # - coco-text/images/train2014
  # - open-images-v7/images/train
val: subset/images/val
  # - WIDER-FACE/WIDER_val/images
  # - coco-text/images/val2014
  # - open-images-v7/images/val

# Classes
names:
  0: Traffic sign
  1: Machine printed
  2: Handwritten
  3: Other text
  4: Face

# Download script/URL (optional) ---------------------------------------------------------------------------------------
download: |
  from dataset_downloaders import (
    download_coco_text, download_open_images_v7, 
    download_wider_face,
  )
  from utils import split_datasets

  download_wider_face()
  download_coco_text()
  download_open_images_v7()
  split_datasets()
